# Generated by Django 2.2.2 on 2019-06-29 11:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicepagerelatedlink_servicespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='aside_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст в левой колонке'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='aside_it',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст в левой колонке'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='aside_ru',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст в левой колонке'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_it',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='text_ru',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
