# Generated by Django 2.2.2 on 2019-06-30 14:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190629_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicescategorypage',
            name='text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='servicescategorypage',
            name='text_it',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='servicescategorypage',
            name='text_ru',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
