# Generated by Django 2.2.2 on 2019-06-27 19:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190627_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug категории прайса')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pricepage',
            name='price_slogan',
        ),
        migrations.DeleteModel(
            name='BlogPageRelatedLink',
        ),
        migrations.AddField(
            model_name='priceitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceitem_p', to='home.PricePage'),
        ),
    ]
