# Generated by Django 2.2.2 on 2019-06-28 03:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0003_auto_20190627_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_slogan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Лозунг страницы')),
                ('text1', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст1')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpecialistsPageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name1', models.CharField(blank=True, max_length=255, verbose_name='ФИО 1')),
                ('job1', models.CharField(blank=True, max_length=255, verbose_name='Должность 1')),
                ('name2', models.CharField(blank=True, max_length=255, verbose_name='ФИО 2')),
                ('job2', models.CharField(blank=True, max_length=255, verbose_name='Должность 2')),
                ('name3', models.CharField(blank=True, max_length=255, verbose_name='ФИО 3')),
                ('job3', models.CharField(blank=True, max_length=255, verbose_name='Должность 3')),
                ('image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Изображение 1')),
                ('image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Изображение 2')),
                ('image3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Изображение 3')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists_carousel_items', to='home.SpecialistsPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
