# Generated by Django 2.2.2 on 2019-06-28 04:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0004_specialistspage_specialistspagecarouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('address_it', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('schedule', models.CharField(blank=True, max_length=250, null=True, verbose_name='Расписание')),
                ('how', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Как добраться')),
                ('how_it', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Как добраться')),
                ('how_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Как добраться')),
                ('how_ru', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Как добраться')),
                ('contact_map', models.TextField(blank=True, help_text='Разместите код карты', null=True, verbose_name='Карта')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={},
        ),
        migrations.AddField(
            model_name='specialistspage',
            name='page_slogan_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Лозунг страницы'),
        ),
        migrations.AddField(
            model_name='specialistspage',
            name='page_slogan_it',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Лозунг страницы'),
        ),
        migrations.AddField(
            model_name='specialistspage',
            name='page_slogan_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Лозунг страницы'),
        ),
    ]
