# Generated by Django 2.2.2 on 2019-06-28 17:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0005_auto_20190628_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст1')),
                ('intro_it', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст1')),
                ('intro_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст1')),
                ('intro_ru', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст1')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
