# Generated by Django 2.2.2 on 2019-06-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0009_auto_20190628_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselPage',
            new_name='CarouselItem',
        ),
    ]
