# Generated by Django 2.2.2 on 2019-06-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190629_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistspage',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
