# Generated by Django 2.2.2 on 2019-06-29 05:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0013_auto_20190629_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='должность')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug категории прайса')),
                ('text', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Изображение')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_item', to='home.TestimonialsPage')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
