# Generated by Django 2.2.2 on 2019-07-01 19:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_feedbackform_2_field_feedbackform_2_page_feedbackform_3_field_feedbackform_3_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform_2_field',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='FBForm_2', to='home.FeedBackForm_2_Page'),
        ),
        migrations.AlterField(
            model_name='feedbackform_3_field',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='FBForm_3', to='home.FeedBackForm_1_Page'),
        ),
    ]
